import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, PenLine } from "lucide-react";

export default function HowItWorksPage() {
  return <main className="min-h-screen bg-[#FAFAF7]"><div className="mx-auto max-w-5xl px-6 py-8 lg:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#14532D]"><ArrowLeft size={16} /> Back home</Link><div className="mt-20 max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.15em] text-[#B45309]">How it works</p><h1 className="mt-3 font-serif text-5xl leading-tight tracking-tight text-stone-900">Learning that respects your attention.</h1><p className="mt-6 text-lg leading-8 text-stone-600">Verdant Learning turns curiosity into a steady practice with focused courses, thoughtful pacing, and useful outcomes.</p></div><div className="mt-16 grid gap-px overflow-hidden rounded-2xl border border-stone-200 bg-stone-200 md:grid-cols-3"><Step icon={<BookOpen />} number="01" title="Choose a direction" text="Browse a focused catalogue and choose a course that fits your interests and time." /><Step icon={<PenLine />} number="02" title="Make steady progress" text="Move through clear lessons in small sessions, whenever your schedule allows." /><Step icon={<CheckCircle2 />} number="03" title="Carry it forward" text="Use what you learn through reflection, practice, and projects that matter." /></div><div className="mt-20 flex flex-col items-start justify-between gap-6 border-t border-stone-200 pt-10 sm:flex-row sm:items-center"><div><h2 className="font-serif text-3xl text-stone-900">Ready to explore?</h2><p className="mt-2 text-stone-600">Start with a course that meets you where you are.</p></div><Link href="/catalogue" className="inline-flex items-center gap-2 rounded-lg bg-[#14532D] px-5 py-3.5 font-semibold text-white hover:bg-[#166534]">Browse courses <ArrowRight size={17} /></Link></div></div></main>;
}

function Step({ icon, number, title, text }: { icon: React.ReactNode; number: string; title: string; text: string }) {
  return <div className="bg-white p-7"><div className="flex items-center justify-between text-[#14532D]"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#ECFDF3]">{icon}</span><span className="text-sm font-bold text-[#B45309]">{number}</span></div><h2 className="mt-8 text-lg font-bold text-stone-900">{title}</h2><p className="mt-3 text-sm leading-6 text-stone-500">{text}</p></div>;
}
