import Link from "next/link";
import { ArrowLeft, ArrowRight, Clock3, Leaf, Search } from "lucide-react";
import { getCatalogueCourses } from "@/lib/courses";

export default async function CataloguePage({ searchParams }: { searchParams: Promise<{ from?: string }> }) {
  const courses = await getCatalogueCourses();
  const fromDashboard = (await searchParams).from === "dashboard";
  const backHref = fromDashboard ? "/dashboard" : "/";
  const backLabel = fromDashboard ? "Back to account home" : "Back to site home";

  return <main className="min-h-screen bg-[#FAFAF7]"><div className="mx-auto max-w-7xl px-6 py-8 lg:px-8"><Link href={backHref} className="inline-flex items-center gap-2 text-sm font-semibold text-[#14532D]"><ArrowLeft size={16} /> {backLabel}</Link><div className="mt-16 max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.15em] text-[#B45309]">Course catalogue</p><h1 className="mt-3 font-serif text-5xl tracking-tight text-stone-900">Find something worth your time.</h1><p className="mt-5 text-lg leading-8 text-stone-600">Practical courses designed to help you think clearly, make useful things, and keep growing.</p></div><div className="mt-10 flex flex-col gap-3 border-y border-stone-200 py-5 sm:flex-row"><label className="flex flex-1 items-center gap-3 rounded-lg border border-stone-300 bg-white px-4 py-3 text-sm text-stone-400"><Search size={18} /><span>Search courses</span></label><button className="rounded-lg border border-stone-300 bg-white px-5 py-3 text-left text-sm font-semibold text-stone-700">All categories</button><button className="rounded-lg border border-stone-300 bg-white px-5 py-3 text-left text-sm font-semibold text-stone-700">All levels</button></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{courses.map((course) => <Link href={`/catalogue?from=${fromDashboard ? "dashboard" : "site"}`} key={course.title} className="group overflow-hidden rounded-xl border border-stone-200 bg-white transition hover:-translate-y-1 hover:border-[#9ac2a3] hover:shadow-lg"><div className={`relative flex h-44 items-end overflow-hidden p-5 ${course.tone}`}><div className="absolute right-5 top-5 flex h-16 w-16 items-center justify-center rounded-full border border-black/10 text-[#14532D]"><Leaf size={28} strokeWidth={1.3} /></div><span className="rounded-full bg-white/75 px-3 py-1 text-xs font-bold text-[#14532D]">{course.category}</span></div><div className="p-5"><h2 className="text-lg font-bold leading-snug text-stone-900 group-hover:text-[#14532D]">{course.title}</h2><div className="mt-5 flex items-center justify-between text-xs text-stone-500"><span>By {course.instructor}</span><span className="flex items-center gap-1"><Clock3 size={14} /> {course.duration}</span></div><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#14532D]">View course <ArrowRight size={15} /></span></div></Link>)}</div></div></main>;
}
